// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4bV0Jo4B10VY_NL1wthixlRsa3g-OXA',
    appId: '1:163490046102:web:f1fc6febb6da33cbfca2b7',
    messagingSenderId: '163490046102',
    projectId: 'anees-maps',
    authDomain: 'anees-maps.firebaseapp.com',
    storageBucket: 'anees-maps.firebasestorage.app',
    measurementId: 'G-DLYRMMV419',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1-ddgYnFL2JC_fTCoKi8a1wCXq6jyc2A',
    appId: '1:163490046102:android:70d1c0cefd30b4affca2b7',
    messagingSenderId: '163490046102',
    projectId: 'anees-maps',
    storageBucket: 'anees-maps.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp4bV0Jo4B10VY_NL1wthixlRsa3g-OXA',
    appId: '1:163490046102:web:6d72db634752c434fca2b7',
    messagingSenderId: '163490046102',
    projectId: 'anees-maps',
    authDomain: 'anees-maps.firebaseapp.com',
    storageBucket: 'anees-maps.firebasestorage.app',
    measurementId: 'G-MCYYVFEYPX',
  );
}
